/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.net.URL;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Item;
import model.Sprint;
import DAOs.CombosDAO;
import DAOs.ItemDAO;
import DAOs.SprintDAO;

/**
 *
 * @author willian
 */
public class FrmRegisterItem
        extends javax.swing.JFrame {

    private static ItemDAO itemTransaction = new ItemDAO();
    private static SprintDAO sprintTransaction = new SprintDAO();
    private Item currentItem;
    int id;

    /**
     * Creates new form FrmRegisterItem
     */
    public FrmRegisterItem() {
        setIconImage(loadImageIcon("/icons/icon-scrum.png").getImage());

        initComponents();
        setTitle("Cadastro de itens");
        CombosDAO combos = new CombosDAO();
        combos.popularCombo("sprint", cbxSprint);

        itemTransaction.setItemsByFilter(tblItem, tfdSearch.getText());
    }

    public void setCurrentItem(Item item) {
        this.currentItem = item;
    }

    public void editContent() {
        id = currentItem.getIdItem();

        tfdTitle.setText(currentItem.getTitle());
        txaInfo.setText(currentItem.getInfo());
        String classification = currentItem.getClassification();
        String type = currentItem.getItemType();

        tfdEstimated.setText(currentItem.getEstimated());
        tfdDuration.setText(currentItem.getDuration());

        ftfStarted.setText(currentItem.getProccessStarted());
        ftfFinished.setText(currentItem.getProccessFinished());

        for (int i = 0; i < cbxSprint.getItemCount(); i++) {
            if (cbxSprint.getItemAt(i).toString().equals(currentItem.getSprint().getAlias())) {
                cbxSprint.setSelectedIndex(i);
            }

        }

        if (classification.equals("Baixo")) {
            cbxClassification.setSelectedIndex(0);
        } else if (classification.equals("Médio")) {
            cbxClassification.setSelectedIndex(1);
        } else if (classification.equals("Alto")) {
            cbxClassification.setSelectedIndex(2);
        } else {
            cbxClassification.setSelectedIndex(3);
        }

        if (currentItem.getStatus() == 1) {
            cbxStatus.setSelectedIndex(0);
        } else if (currentItem.getStatus() == 2) {
            cbxStatus.setSelectedIndex(1);
        } else {
            cbxStatus.setSelectedIndex(3);
        }

        if (type.equals("Planejado")) {
            cbxType.setSelectedIndex(0);
        } else {
            cbxType.setSelectedIndex(1);
        }

        tbdItem.setSelectedIndex(0);
    }

    private void clear() {
        tfdDuration.setText("");
        tfdEstimated.setText("");
        tfdSearch.setText("");
        tfdTitle.setText("");
        ftfFinished.setText("");
        ftfStarted.setText("");

        txaInfo.setText("");
        cbxClassification.setSelectedIndex(0);
        cbxSprint.setSelectedIndex(0);
        cbxStatus.setSelectedIndex(0);
        cbxType.setSelectedIndex(0);

        id = 0;
    }

    private static ImageIcon loadImageIcon(String path) {
        URL imgURL = FrmRegisterItem.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        tbdItem = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        cbxType = new javax.swing.JComboBox();
        ftfStarted = new javax.swing.JFormattedTextField();
        ftfFinished = new javax.swing.JFormattedTextField();
        cbxStatus = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaInfo = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbxSprint = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfdTitle = new javax.swing.JTextField();
        cbxClassification = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfdEstimated = new javax.swing.JTextField();
        tfdDuration = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfdSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSave.setText("Salvar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDel.setText("Excluir");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnClose.setText("Fechar");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnNew.setText("Novo");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnEdit.setText("Editar");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        tbdItem.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tbdItemStateChanged(evt);
            }
        });

        cbxType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Planejado", "Speed Lane" }));

        ftfStarted.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        ftfFinished.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        cbxStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TO DO", "IN PROGRESS", "DONE" }));

        jLabel6.setText("Tipo:");

        jLabel3.setText("Classificação:");

        txaInfo.setColumns(20);
        txaInfo.setRows(5);
        jScrollPane2.setViewportView(txaInfo);

        jLabel4.setText("Título:");

        jLabel11.setText("Fim (dd/mm/yyyy):");

        jLabel5.setText("Descrição:");

        jLabel9.setText("Duração (em minutos):");

        jLabel8.setText("Estimado (em minutos):");

        jLabel10.setText("Início (dd/mm/yyyy):");

        cbxClassification.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Baixo", "Médio", "Alto", "Muito Alto" }));

        jLabel7.setText("Estado:");

        jLabel2.setText("Sprint:");

        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("*");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("*");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("*");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("*");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("*");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        jLabel24.setText("*");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setText("*");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 0, 0));
        jLabel26.setText("*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbxSprint, 0, 323, Short.MAX_VALUE)
                        .addComponent(cbxClassification, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbxType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbxStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfdTitle))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ftfStarted)
                    .addComponent(ftfFinished)
                    .addComponent(tfdEstimated)
                    .addComponent(tfdDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfdEstimated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addComponent(tfdDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftfStarted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addComponent(ftfFinished, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbxSprint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbxClassification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfdTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jLabel21))
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel26)))))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        tbdItem.addTab("Cadastrar", jPanel1);

        jLabel1.setText("Pesquisar Item de Sprint:");

        btnSearch.setText("Pesquisar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblItem);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tfdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE))
        );

        tbdItem.addTab("Editar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addComponent(tbdItem)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tbdItem)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnDel)
                    .addComponent(btnNew)
                    .addComponent(btnEdit)
                    .addComponent(btnClose))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSaveActionPerformed
    {//GEN-HEADEREND:event_btnSaveActionPerformed
        Item item = new Item();

        boolean result = false, validate = false;
        //campos obrigatorios
        if (!(tfdTitle.getText().isEmpty()) && !(txaInfo.getText().equals(""))
                && cbxSprint.getSelectedIndex() != 0) {
            Sprint sprint = sprintTransaction.getSprintByAlias(cbxSprint.getSelectedItem().toString());

            item.setTitle(tfdTitle.getText());
            item.setInfo(txaInfo.getText());
            item.setSprint(sprint);
            if (!tfdDuration.getText().isEmpty()) {
                item.setDuration(tfdDuration.getText());
            } else {
                item.setDuration("0");
            }
            item.setEstimated(tfdEstimated.getText());
            item.setProccessStarted(ftfStarted.getText());

            if (!ftfFinished.getText().isEmpty()) {
                item.setProccessFinished(ftfFinished.getText());
            } else {
                item.setProccessFinished(null);
            }

            //seta o status do item
            if (cbxStatus.getSelectedIndex() == 0) {
                item.setStatus(1);
            } else if (cbxStatus.getSelectedIndex() == 1) {
                item.setStatus(2);
            } else {
                item.setStatus(3);
            }

            //seta a classificação do item
            if (cbxClassification.getSelectedIndex() == 0) {
                item.setClassification("Baixo");
            } else if (cbxClassification.getSelectedIndex() == 1) {
                item.setClassification("Médio");
            } else if (cbxClassification.getSelectedIndex() == 0) {
                item.setClassification("Alto");
            } else {
                item.setClassification("Muito Alto");
            }

            //seta o tipo do item
            if (cbxType.getSelectedIndex() == 0) {
                item.setItemType("Planejado");
            } else {
                item.setItemType("Speed Lane");
            }
            validate = true;
        } else {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos obrigatórios");
            validate = false;
        }

        if (validate && id == 0) {
            result = itemTransaction.insertItem(item);
            itemTransaction.setItemsByFilter(tblItem, "");
        } else if (validate && id > 0) {
            result = itemTransaction.updateItem(id, item);
            itemTransaction.setItemsByFilter(tblItem, "");
        }

        if (validate && result && id == 0) {
            JOptionPane.showMessageDialog(rootPane, "Item inserido com sucesso.");
            clear();
        } else if (validate && result && id > 0) {
            JOptionPane.showMessageDialog(this, "Item atualizado com sucesso");
            clear();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Erro ao inserir ou atualizar item.");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDelActionPerformed
    {//GEN-HEADEREND:event_btnDelActionPerformed

        if (tblItem.getSelectedRow() >= 0) {
            int id = (Integer) tblItem.getValueAt(tblItem.getSelectedRow(), 0);

            if (itemTransaction.deleteItem(id)) {
                JOptionPane.showMessageDialog(null, "Registro excluido.");
                itemTransaction.setItemsByFilter(tblItem, "");
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao deletar item.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor selecione um registro");
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCloseActionPerformed
    {//GEN-HEADEREND:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNewActionPerformed
    {//GEN-HEADEREND:event_btnNewActionPerformed
        clear();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEditActionPerformed
    {//GEN-HEADEREND:event_btnEditActionPerformed
        if (tblItem.getSelectedRow() >= 0) {
            id = (Integer) tblItem.getValueAt(tblItem.getSelectedRow(), 0);

            tfdTitle.setText((String) tblItem.getValueAt(tblItem.getSelectedRow(), 1));
            txaInfo.setText((String) tblItem.getValueAt(tblItem.getSelectedRow(), 2));
            String classification = (String) tblItem.getValueAt(tblItem.getSelectedRow(), 3);
            String type = (String) tblItem.getValueAt(tblItem.getSelectedRow(), 4);
            String status = (String) tblItem.getValueAt(tblItem.getSelectedRow(), 5);
            tfdEstimated.setText(String.valueOf((Integer) tblItem.getValueAt(tblItem.getSelectedRow(), 6)));
            tfdDuration.setText(String.valueOf((Integer) tblItem.getValueAt(tblItem.getSelectedRow(), 7)));

            ftfStarted.setText((String) tblItem.getValueAt(tblItem.getSelectedRow(), 8));
            ftfFinished.setText( ( (String) tblItem.getValueAt(tblItem.getSelectedRow(), 9) ).equals("n/d") ? "" : (String) tblItem.getValueAt(tblItem.getSelectedRow(), 9) );

            for (int i = 0; i < cbxSprint.getItemCount(); i++) {
                if (cbxSprint.getItemAt(i).toString().equals((String) tblItem.getValueAt(tblItem.getSelectedRow(), 10))) {
                    cbxSprint.setSelectedIndex(i);
                }

            }

            if (classification.equals("Baixo")) {
                cbxClassification.setSelectedIndex(0);
            } else if (classification.equals("Médio")) {
                cbxClassification.setSelectedIndex(1);
            } else if (classification.equals("Alto")) {
                cbxClassification.setSelectedIndex(2);
            } else {
                cbxClassification.setSelectedIndex(3);
            }

            if (status.equals("TO DO")) {
                cbxStatus.setSelectedIndex(0);
            } else if (status.equals("IN PROGRESS")) {
                cbxStatus.setSelectedIndex(1);
            } else {
                cbxStatus.setSelectedIndex(2);
            }

            if (type.equals("Planejado")) {
                cbxType.setSelectedIndex(0);
            } else {
                cbxType.setSelectedIndex(1);
            }

            tbdItem.setSelectedIndex(0);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor selecione um registro");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        itemTransaction.setItemsByFilter(tblItem, tfdSearch.getText());
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tbdItemStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tbdItemStateChanged
        if (tbdItem.getSelectedIndex() == 0) {
            btnDel.setEnabled(false);
        } else {
            btnDel.setEnabled(true);
        }
    }//GEN-LAST:event_tbdItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegisterItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegisterItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegisterItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegisterItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegisterItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox cbxClassification;
    private javax.swing.JComboBox cbxSprint;
    private javax.swing.JComboBox cbxStatus;
    private javax.swing.JComboBox cbxType;
    private javax.swing.JFormattedTextField ftfFinished;
    private javax.swing.JFormattedTextField ftfStarted;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane tbdItem;
    private javax.swing.JTable tblItem;
    private javax.swing.JTextField tfdDuration;
    private javax.swing.JTextField tfdEstimated;
    private javax.swing.JTextField tfdSearch;
    private javax.swing.JTextField tfdTitle;
    private javax.swing.JTextArea txaInfo;
    // End of variables declaration//GEN-END:variables

}
