/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.event.KeyEvent;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Address;
import model.User;
import DAOs.TeamDAO;
import DAOs.UserDAO;

/**
 *
 * @author willian
 */
public class FrmRegisterUser
        extends javax.swing.JFrame
{
    UserDAO userTransactions = new UserDAO();
    TeamDAO teamTransactions = new TeamDAO();
    int id, idAddress;
    /**
     * Creates new form FrmRegisterUse
     */
    public FrmRegisterUser()
    {
        setIconImage( loadImageIcon("/icons/icon-scrum.png").getImage() );
        initComponents();
        setTitle( "Cadastro de usuários" );
        userTransactions.setItensByFilter( tblUser, "" );
        teamTransactions.setItensByFilter(tblTeam, "");
        id=0;
    }
    
    private static ImageIcon loadImageIcon(String path) {
        URL imgURL = FrmRegisterUser.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
    }
    
    private void clear()
    {
        ftfPhone.setText( "" );
        pfd1.setText( "" );
        pfd2.setText( "" );
        tfdAddress.setText( "" );
        tfdCity.setText( "" );
        tfdDistrict.setText( "" );
        tfdEmail.setText( "" );
        tfdName.setText( "" );
        tfdState.setText( "" );
        tfdUf.setText( "" );
        cbxUserType.setSelectedIndex( 0 );
        tfdlogin.setText( "" );
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        tbdUser = new javax.swing.JTabbedPane();
        pnlRegisterUser = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfdName = new javax.swing.JTextField();
        tfdEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ftfPhone = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        tfdlogin = new javax.swing.JTextField();
        cbxUserType = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pfd1 = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        pfd2 = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        tfdTeam = new javax.swing.JTextField();
        btnSearchTeam = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTeam = new javax.swing.JTable();
        lblPasswordsEquals = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfdState = new javax.swing.JTextField();
        tfdDistrict = new javax.swing.JTextField();
        tfdAddress = new javax.swing.JTextField();
        tfdUf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfdCity = new javax.swing.JTextField();
        pnlEditUser = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        tfdSearch = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbdUser.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                tbdUserStateChanged(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Dados obrigatórios do Sistema:");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("Dados Adicionais");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Nome:");

        tfdName.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                tfdNameFocusLost(evt);
            }
        });

        tfdEmail.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                tfdEmailFocusLost(evt);
            }
        });

        jLabel2.setText("E-mail:");

        jLabel3.setText("Telefone:");

        try
        {
            ftfPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex)
        {
            ex.printStackTrace();
        }

        jLabel4.setText("Login:");

        tfdlogin.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                tfdloginFocusLost(evt);
            }
        });

        cbxUserType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Visualizador", "Operador", "Administrador", "Super-usuário" }));

        jLabel6.setText("Tipo de usuário:");

        jLabel5.setText("Senha:");

        pfd1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                pfd1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Repita a senha:");

        pfd2.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                pfd2FocusLost(evt);
            }
        });
        pfd2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                pfd2ActionPerformed(evt);
            }
        });

        jLabel16.setText("Equipe:");

        tfdTeam.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                tfdTeamKeyPressed(evt);
            }
        });

        btnSearchTeam.setText("Pesquisar");
        btnSearchTeam.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSearchTeamActionPerformed(evt);
            }
        });

        tblTeam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblTeam);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(cbxUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(ftfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(95, 95, 95)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfdEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(tfdlogin)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(pfd1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(pfd2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(lblPasswordsEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(334, 334, 334)
                        .addComponent(btnSearchTeam))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfdName, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(tfdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(tfdEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(ftfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tfdlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbxUserType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(pfd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(pfd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblPasswordsEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchTeam)
                    .addComponent(tfdTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("Endereço:");

        jLabel8.setText("Bairro:");

        jLabel11.setText("Estado:");

        tfdState.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tfdStateActionPerformed(evt);
            }
        });

        tfdDistrict.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tfdDistrictActionPerformed(evt);
            }
        });

        tfdUf.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tfdUfActionPerformed(evt);
            }
        });

        jLabel12.setText("UF:");

        jLabel9.setText("Cidade:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfdAddress)
                        .addComponent(tfdDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfdState, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(142, 142, 142)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfdUf, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdCity, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfdCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tfdAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfdDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfdState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(tfdUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout pnlRegisterUserLayout = new javax.swing.GroupLayout(pnlRegisterUser);
        pnlRegisterUser.setLayout(pnlRegisterUserLayout);
        pnlRegisterUserLayout.setHorizontalGroup(
            pnlRegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterUserLayout.createSequentialGroup()
                .addGroup(pnlRegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegisterUserLayout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jLabel14))
                    .addGroup(pnlRegisterUserLayout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jLabel15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlRegisterUserLayout.setVerticalGroup(
            pnlRegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterUserLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(74, 74, 74))
        );

        tbdUser.addTab("Cadastrar", pnlRegisterUser);

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUser);

        tfdSearch.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                tfdSearchKeyPressed(evt);
            }
        });

        jLabel13.setText("Pesquisar Usuário:");

        btnSearch.setText("Pesquisar");
        btnSearch.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEditUserLayout = new javax.swing.GroupLayout(pnlEditUser);
        pnlEditUser.setLayout(pnlEditUserLayout);
        pnlEditUserLayout.setHorizontalGroup(
            pnlEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(pnlEditUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(tfdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addContainerGap(356, Short.MAX_VALUE))
        );
        pnlEditUserLayout.setVerticalGroup(
            pnlEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditUserLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(btnSearch))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );

        tbdUser.addTab("Editar", pnlEditUser);

        btnSave.setText("Salvar");
        btnSave.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSaveActionPerformed(evt);
            }
        });

        btnDel.setText("Excluir");
        btnDel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDelActionPerformed(evt);
            }
        });

        btnNew.setText("Novo");
        btnNew.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNewActionPerformed(evt);
            }
        });

        btnEdit.setText("Editar");
        btnEdit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEditActionPerformed(evt);
            }
        });

        btnClose.setText("Fechar");
        btnClose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbdUser)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnDel)
                    .addComponent(btnNew)
                    .addComponent(btnEdit)
                    .addComponent(btnClose))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSaveActionPerformed
    {//GEN-HEADEREND:event_btnSaveActionPerformed
        User user = new User();
        Address address = new Address();
        boolean validate;
        if ( !tfdName.getText().equals( "" ) && !tfdEmail.getText().equals( "" ) && 
                !tfdlogin.getText().equals( "" ) && 
                !pfd1.getText().equals( "" ) && !pfd2.getText().equals( "" )  )  
        {
            user.setName( tfdName.getText() );
            user.setEmail( tfdEmail.getText() );
            user.setPhone( ftfPhone.getText() );
            user.setLogin( tfdlogin.getText() );
            user.setPassword( pfd2.getText() );
            int userType ;
            if (cbxUserType.getSelectedIndex() == 0) {
                userType = 2;
            }
            else if (cbxUserType.getSelectedIndex() == 1) {
                userType = 3;
            }
            else if (cbxUserType.getSelectedIndex() == 2) {
                userType = 4;
            }
            else {
                userType = 5;
            }
                
            user.setUserType( userType );
            
            address.setAddress( tfdAddress.getText() );
            address.setDistrict( tfdDistrict.getText() );
            address.setCity( tfdCity.getText() );
            address.setState( tfdState.getText() );
            address.setUf( tfdUf.getText() );
            address.setIdAddress(idAddress);
            validate = true;
        }
        else
        {
            JOptionPane.showMessageDialog( this, "Os campos: Nome, login, E-mail, Login, Senha e Tipo não podem estar em branco" );
            validate = false;
        }
        boolean  validatePWD = false, validateLogin = false, result= false;
        
        //valida se o login já existe no banco
        validateLogin = userTransactions.validateDuplicatedUserByLogin( user );
        if ( !validateLogin && id == 0)
        {
            JOptionPane.showMessageDialog( this, "Login já existe." );
            validateLogin = false;
            
        }
        
        //caso senhas não seja iguais
        if( pfd1.getText().equals( pfd2.getText()) )
        {
            validatePWD = true;
        }
        else
        {
            validatePWD = false;
        }
        
        if ( tblTeam.getSelectedRow() >= 0 ) 
        {
            user.setRefTeam( (Integer) tblTeam.getValueAt( tblTeam.getSelectedRow() , 0 ) );
        }
        
        if ( validatePWD && validateLogin && id == 0 && validate )
        {
            result = userTransactions.insertUser( user, address );
            userTransactions.setItensByFilter( tblUser, "" );
            teamTransactions.setItensByFilter(tblTeam, "");
            teamTransactions.updateTotalParticipants( user.getRefTeam() );
            clear();
        }
        
        else if( id > 0 )
        {
            result = userTransactions.updateUser( id , user, address );
            userTransactions.setItensByFilter( tblUser, "" );
            teamTransactions.setItensByFilter(tblTeam, "");
            clear();
        }
        
        
        if( result && id == 0)
        {
            JOptionPane.showMessageDialog( rootPane, "Usuário inserido com sucesso." );
            id = 0;
        }
        
        else if ( id > 0 )
        {
            JOptionPane.showMessageDialog(this, "Usuário atualizado atualizado com sucesso" );
            id = 0;
        }
        
        else
        {
            JOptionPane.showMessageDialog( rootPane, "Erro ao inserir ou atualizar usuário.");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSearchActionPerformed
    {//GEN-HEADEREND:event_btnSearchActionPerformed
      userTransactions.setItensByFilter( tblUser, tfdSearch.getText() );
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDelActionPerformed
    {//GEN-HEADEREND:event_btnDelActionPerformed
        
        if ( tblUser.getSelectedRow() >= 0 )
        {
            int id = (Integer) tblUser.getValueAt( tblUser.getSelectedRow(), 0);
            
            if ( userTransactions.deleteUser( id ) )
            {
                teamTransactions.decreaseTotalParticipants( (Integer) tblUser.getValueAt( tblUser.getSelectedRow(), 7 ) );
                JOptionPane.showMessageDialog( null, "Registro excluido.");
                userTransactions.setItensByFilter( tblUser, "" );
            }
            else
            {
                JOptionPane.showMessageDialog( null, "Erro ao deletar usuário." );
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Por favor selecione um registro");
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void tfdStateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tfdStateActionPerformed
    {//GEN-HEADEREND:event_tfdStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdStateActionPerformed

    private void tfdDistrictActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tfdDistrictActionPerformed
    {//GEN-HEADEREND:event_tfdDistrictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdDistrictActionPerformed

    private void tfdUfActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tfdUfActionPerformed
    {//GEN-HEADEREND:event_tfdUfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdUfActionPerformed

    private void pfd2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_pfd2ActionPerformed
    {//GEN-HEADEREND:event_pfd2ActionPerformed

    }//GEN-LAST:event_pfd2ActionPerformed

    private void pfd2FocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_pfd2FocusLost
    {//GEN-HEADEREND:event_pfd2FocusLost
        if ( ! pfd1.getText().equals( pfd2.getText() ) )
        {
            lblPasswordsEquals.setText( "Senhas não conferem." );
        }
        else
        {
            lblPasswordsEquals.setText( "conferem." );
        }
    }//GEN-LAST:event_pfd2FocusLost

    private void pfd1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_pfd1ActionPerformed
    {//GEN-HEADEREND:event_pfd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfd1ActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNewActionPerformed
    {//GEN-HEADEREND:event_btnNewActionPerformed
        clear();
        id = 0;
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEditActionPerformed
    {//GEN-HEADEREND:event_btnEditActionPerformed
         if ( tblUser.getSelectedRow() >= 0 )
        {
            id = (Integer) tblUser.getValueAt( tblUser.getSelectedRow(), 0);
            ftfPhone.setText( (String) tblUser.getValueAt( tblUser.getSelectedRow(), 3) );
            pfd1.setText( (String) tblUser.getValueAt( tblUser.getSelectedRow(), 5 ) );
            pfd2.setText( (String) tblUser.getValueAt( tblUser.getSelectedRow(), 5 ) );
            tfdEmail.setText( (String) tblUser.getValueAt( tblUser.getSelectedRow(), 2 ) );
            tfdName.setText( (String) tblUser.getValueAt( tblUser.getSelectedRow(), 1 ) );
            int type = (Integer) tblUser.getValueAt( tblUser.getSelectedRow(), 6);
            // set cbx selected index
            if ( type == 2)
            {
                cbxUserType.setSelectedIndex( 0 );
            } 
            else if ( type == 3)
            {
                cbxUserType.setSelectedIndex( 1 );
            } 
            else if ( type == 4 )
            {
                cbxUserType.setSelectedIndex( 2 );
            } 
            else
            {
                cbxUserType.setSelectedIndex( 3);
            }
            tfdlogin.setText( (String) tblUser.getValueAt( tblUser.getSelectedRow(), 4 ) );
            
            Address a = userTransactions.getAddressByLogin( (String) tblUser.getValueAt( tblUser.getSelectedRow(), 4 ) );
            
            if ( a != null )
            {
                tfdAddress.setText( a.getAddress() );
                tfdCity.setText( a.getCity() );
                tfdDistrict.setText( a.getDistrict() );
                tfdState.setText( a.getState());
                tfdUf.setText( a.getUf() );
                idAddress = a.getIdAddress();
            }
            else
            {
                tfdAddress.setText( "" );
                tfdCity.setText( "" );
                tfdDistrict.setText( "" );
                tfdState.setText( "" );
                tfdUf.setText( "" );
            }
            
            tbdUser.setSelectedIndex( 0 );
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Por favor selecione um registro");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCloseActionPerformed
    {//GEN-HEADEREND:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void tbdUserStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_tbdUserStateChanged
    {//GEN-HEADEREND:event_tbdUserStateChanged
         if ( tbdUser.getSelectedIndex() == 0) {
            btnDel.setEnabled(false);
        } else {
            btnDel.setEnabled(true);
        }
    }//GEN-LAST:event_tbdUserStateChanged

    private void tfdNameFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_tfdNameFocusLost
    {//GEN-HEADEREND:event_tfdNameFocusLost
       
    }//GEN-LAST:event_tfdNameFocusLost

    private void tfdEmailFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_tfdEmailFocusLost
    {//GEN-HEADEREND:event_tfdEmailFocusLost
        
    }//GEN-LAST:event_tfdEmailFocusLost

    private void tfdloginFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_tfdloginFocusLost
    {//GEN-HEADEREND:event_tfdloginFocusLost
     
    }//GEN-LAST:event_tfdloginFocusLost

    private void btnSearchTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchTeamActionPerformed
        teamTransactions.setItensByFilter( tblTeam, tfdTeam.getText() );
    }//GEN-LAST:event_btnSearchTeamActionPerformed

    private void tfdTeamKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfdTeamKeyPressed
    {//GEN-HEADEREND:event_tfdTeamKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            teamTransactions.setItensByFilter( tblTeam, tfdTeam.getText() );
        }
    }//GEN-LAST:event_tfdTeamKeyPressed

    private void tfdSearchKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfdSearchKeyPressed
    {//GEN-HEADEREND:event_tfdSearchKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            userTransactions.setItensByFilter( tblUser, tfdSearch.getText() );
        }
            
    }//GEN-LAST:event_tfdSearchKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] )
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
            {
                if ( "Nimbus".equals( info.getName() ) )
                {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        }
        catch ( ClassNotFoundException ex )
        {
            java.util.logging.Logger.getLogger(FrmRegisterUser.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( InstantiationException ex )
        {
            java.util.logging.Logger.getLogger(FrmRegisterUser.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( IllegalAccessException ex )
        {
            java.util.logging.Logger.getLogger(FrmRegisterUser.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( javax.swing.UnsupportedLookAndFeelException ex )
        {
            java.util.logging.Logger.getLogger(FrmRegisterUser.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FrmRegisterUser().setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchTeam;
    private javax.swing.JComboBox cbxUserType;
    private javax.swing.JFormattedTextField ftfPhone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPasswordsEquals;
    private javax.swing.JPasswordField pfd1;
    private javax.swing.JPasswordField pfd2;
    private javax.swing.JPanel pnlEditUser;
    private javax.swing.JPanel pnlRegisterUser;
    private javax.swing.JTabbedPane tbdUser;
    private javax.swing.JTable tblTeam;
    private javax.swing.JTable tblUser;
    private javax.swing.JTextField tfdAddress;
    private javax.swing.JTextField tfdCity;
    private javax.swing.JTextField tfdDistrict;
    private javax.swing.JTextField tfdEmail;
    private javax.swing.JTextField tfdName;
    private javax.swing.JTextField tfdSearch;
    private javax.swing.JTextField tfdState;
    private javax.swing.JTextField tfdTeam;
    private javax.swing.JTextField tfdUf;
    private javax.swing.JTextField tfdlogin;
    // End of variables declaration//GEN-END:variables
}
