/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package parts;

import DAOs.ItemDAO;
import DAOs.TaskDAO;
import java.awt.Point;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import model.Item;
import model.Sprint;
import model.Task;
import views.FrmRegisterItem;
import views.FrmRegisterTask;

/**
 *
 * @author wav
 */
public class Tasks
        extends javax.swing.JPanel
{
    
    ItemDAO itemManager = new ItemDAO();
    TaskDAO taskManager = new TaskDAO();
    Sprint sprint;

    /**
     * Creates new form Backlog
     */
//    public Tasks()
//    {
//        initComponents();
//    }
//    
    public Item getSelectedItem( JTable table )
    {
        if ( table.getSelectedRow() >= 0 ) {
            return itemManager.getItemById( (Integer) table.getValueAt(table.getSelectedRow() , 0) );
        }
        return null;
    }
    
    public Task getSelectedTask( JTable table )
    {
        if ( table.getSelectedRow() >= 0 ) {
            return taskManager.getTaskById((Integer) table.getValueAt(table.getSelectedRow() , 0) );
        }
        return null;
    }
    
    public Tasks( Sprint sprint )
    {
        initComponents();
        
        this.sprint = sprint;
        
        itemManager.setItemsToDo(tblItemsTodo, "", sprint);
        itemManager.setItemsInProgress(tblItemsWork, "", sprint);
        itemManager.setItemsDone(tblItensDone, "", sprint);
        
        taskManager.setTasks(tblTasksTodo, 1, sprint);
        taskManager.setTasks(tblTasksWork, 2, sprint);
        taskManager.setTasks(tblTasksDone, 3, sprint);
    }
    
    public void setContent( JPanel panel, Sprint sprint )
    {
        this.sprint = sprint;
        
        panel.removeAll();
        
        Tasks tasks = new Tasks( sprint );
        tasks.setVisible( true );
        tasks.setBounds( 0, 0, panel.getWidth(), panel.getHeight() );
        
        panel.add( tasks );
        
        panel.revalidate();
        panel.repaint();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlTODO = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItemsTodo = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblTasksTodo = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnlINPROGRESS = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblItemsWork = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblTasksWork = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlDONE = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblItensDone = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblTasksDone = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        tblItemsTodo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblItemsTodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemsTodoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblItemsTodo);

        tblTasksTodo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTasksTodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTasksTodoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblTasksTodo);

        jLabel3.setText("TAREFAS");

        jLabel6.setText("ITEMS");

        javax.swing.GroupLayout pnlTODOLayout = new javax.swing.GroupLayout(pnlTODO);
        pnlTODO.setLayout(pnlTODOLayout);
        pnlTODOLayout.setHorizontalGroup(
            pnlTODOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
            .addComponent(jScrollPane4)
            .addGroup(pnlTODOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTODOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTODOLayout.setVerticalGroup(
            pnlTODOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTODOLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("TO DO", pnlTODO);

        tblItemsWork.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblItemsWork.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemsWorkMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblItemsWork);

        tblTasksWork.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTasksWork.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTasksWorkMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblTasksWork);

        jLabel2.setText("TAREFAS");

        jLabel5.setText("ITEMS");

        javax.swing.GroupLayout pnlINPROGRESSLayout = new javax.swing.GroupLayout(pnlINPROGRESS);
        pnlINPROGRESS.setLayout(pnlINPROGRESSLayout);
        pnlINPROGRESSLayout.setHorizontalGroup(
            pnlINPROGRESSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addGroup(pnlINPROGRESSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlINPROGRESSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlINPROGRESSLayout.setVerticalGroup(
            pnlINPROGRESSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlINPROGRESSLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("WORK", pnlINPROGRESS);

        tblItensDone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblItensDone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItensDoneMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblItensDone);

        tblTasksDone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTasksDone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTasksDoneMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblTasksDone);

        jLabel1.setText("TAREFAS");

        jLabel4.setText("ITEMS");

        javax.swing.GroupLayout pnlDONELayout = new javax.swing.GroupLayout(pnlDONE);
        pnlDONE.setLayout(pnlDONELayout);
        pnlDONELayout.setHorizontalGroup(
            pnlDONELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
            .addComponent(jScrollPane6)
            .addGroup(pnlDONELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDONELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDONELayout.setVerticalGroup(
            pnlDONELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDONELayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("DONE", pnlDONE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblItemsTodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemsTodoMouseClicked
        Item item =  new Item();
        Point p = evt.getPoint();
        int row = tblItemsTodo.rowAtPoint(p);
        if ( evt.getClickCount() == 2  ) {
            if (tblItemsTodo.getSelectedRow() >= 0) {
                item = getSelectedItem(tblItemsTodo);
                FrmRegisterItem registerItem = new FrmRegisterItem();
                registerItem.setVisible(true);
                registerItem.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);

                registerItem.setCurrentItem(item);
                registerItem.editContent();
            }
//            evt.consume();
        }
        
        else
        {
            if (tblItemsTodo.getSelectedRow() >= 0) {
                item = getSelectedItem(tblItemsTodo);
                taskManager.setTasksByItem(tblTasksTodo, sprint, item, 1);
            }
        }
    }//GEN-LAST:event_tblItemsTodoMouseClicked

    private void tblTasksTodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTasksTodoMouseClicked
        Point p = evt.getPoint();
        
        int row = tblTasksTodo.rowAtPoint(p);
        
        if ( evt.getClickCount() == 2  ) {
            if (tblTasksTodo.getSelectedRow() >= 0) {
                FrmRegisterTask registerTask = new FrmRegisterTask();
                registerTask.setVisible(true);
                registerTask.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
                registerTask.setCurrentTask( taskManager.getTaskById( (Integer) tblTasksTodo.getValueAt(tblTasksTodo.getSelectedRow(), 0) ) );
                registerTask.editContent();
            }
        }
    }//GEN-LAST:event_tblTasksTodoMouseClicked

    private void tblItemsWorkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemsWorkMouseClicked
        Item item =  new Item();
        Point p = evt.getPoint();
        int row = tblItemsWork.rowAtPoint(p);
        if ( evt.getClickCount() == 2  ) {
            
            if (tblItemsWork.getSelectedRow() >= 0) {
                item = getSelectedItem(tblItemsWork);
                FrmRegisterItem registerItem = new FrmRegisterItem();
                registerItem.setVisible(true);
                registerItem.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);

                registerItem.setCurrentItem(item);
                registerItem.editContent();
            }
//            evt.consume();
        }
        
        else
        {
            if (tblItemsWork.getSelectedRow() >= 0) {
                item = getSelectedItem(tblItemsWork);
                taskManager.setTasksByItem(tblTasksWork, sprint, item, 2);
            }
        }
    }//GEN-LAST:event_tblItemsWorkMouseClicked

    private void tblTasksWorkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTasksWorkMouseClicked
        Point p = evt.getPoint();
        
        int row = tblTasksWork.rowAtPoint(p);
        
        if ( evt.getClickCount() == 2  ) {
            
            if (tblTasksWork.getSelectedRow() >= 0) {
                FrmRegisterTask registerTask = new FrmRegisterTask();
                registerTask.setVisible(true);
                registerTask.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
                registerTask.setCurrentTask( taskManager.getTaskById( (Integer) tblTasksWork.getValueAt(tblTasksWork.getSelectedRow(), 0) ) );
                registerTask.editContent();
            }
        }
    }//GEN-LAST:event_tblTasksWorkMouseClicked

    private void tblItensDoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItensDoneMouseClicked
        Item item =  new Item();
        Point p = evt.getPoint();
        int row = tblItensDone.rowAtPoint(p);
        if ( evt.getClickCount() == 2  ) {
//            evt.consume();
            if (tblItensDone.getSelectedRow() >= 0) {
                item = getSelectedItem(tblItensDone);
                FrmRegisterItem registerItem = new FrmRegisterItem();
                registerItem.setVisible(true);
                registerItem.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);

                registerItem.setCurrentItem(item);
                registerItem.editContent();
            }
        }
        
        else
        {
            if (tblItensDone.getSelectedRow() >= 0) {
                item = getSelectedItem(tblItensDone);
                taskManager.setTasksByItem(tblTasksDone, sprint, item, 3);
            }
        }
    }//GEN-LAST:event_tblItensDoneMouseClicked

    private void tblTasksDoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTasksDoneMouseClicked
        Point p = evt.getPoint();
        
        int row = tblTasksDone.rowAtPoint(p);
        
        if ( evt.getClickCount() == 2  ) {
            
            if (tblTasksDone.getSelectedRow() >= 0) {
                FrmRegisterTask registerTask = new FrmRegisterTask();
                registerTask.setVisible(true);
                registerTask.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);

                registerTask.setCurrentTask( taskManager.getTaskById( (Integer) tblTasksDone.getValueAt(tblTasksDone.getSelectedRow(), 0) ) );
                registerTask.editContent();
            }
        }
    }//GEN-LAST:event_tblTasksDoneMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnlDONE;
    private javax.swing.JPanel pnlINPROGRESS;
    private javax.swing.JPanel pnlTODO;
    private javax.swing.JTable tblItemsTodo;
    private javax.swing.JTable tblItemsWork;
    private javax.swing.JTable tblItensDone;
    private javax.swing.JTable tblTasksDone;
    private javax.swing.JTable tblTasksTodo;
    private javax.swing.JTable tblTasksWork;
    // End of variables declaration//GEN-END:variables
}
